In [11]:
import numpy as np

In [4]:
!pip install numpy

In [8]:
!pwd

/home/rakesh


In [23]:
#0 Dimension array

a = np.array(43)
print(type(a))

<class 'numpy.ndarray'>


In [27]:
#1Dimension array:

arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [39]:
#Creating a 2-D array

arr_2d=np.array([[1,2,3],[4,5,6],[5,6,8]])
print(arr_2d)
print(type(arr_2d))
print(arr_2d.shape)

[[1 2 3]
 [4 5 6]
 [5 6 8]]
<class 'numpy.ndarray'>
(3, 3)


In [41]:
#Example

x = np.array(42)
y = np.array([1, 2, 3, 4, 5])
z = np.array([[1, 2, 3], [4, 5, 6]])
v = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(x)
print(y)
print(z)
print(v)

42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [43]:
#Datatypes and Memory Storage in NumPy Arrays
#Example 1 :

arr1 = np.array([1, 2, 3, 4, 5], dtype=int)
print("Example #1:")
print("Array:", arr1)
print("Data type:", arr1.dtype)
print()

Example #1:
Array: [1 2 3 4 5]
Data type: int64



In [49]:
#Example 2 :

arr2 = np.array([1, 2, 3, 4, 5], dtype=np.int8)
print("Example #2:")
print("Array:", arr2)
print("Data type:", arr2.dtype)
print()

Example #2:
Array: [1 2 3 4 5]
Data type: int8



In [51]:
#Example 3 

arr3 = np.array([1, 2, 3, 4, 5], dtype='i2')
print("Example #3:")
print("Array:", arr3)
print("Data type:", arr3.dtype)

Example #3:
Array: [1 2 3 4 5]
Data type: int16


In [53]:
#Example 

arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [55]:
#creating numpy array using the list

x=[12,32,43,2,2,12,3,5]
a=np.array(x)
print(type(a))
print(a)

<class 'numpy.ndarray'>
[12 32 43  2  2 12  3  5]


In [59]:
#Example 2 

x=[[1,2,3,4,5],[6,7,8,9,10]]
a=np.asarray(x)
print(type(a))
print(a)

<class 'numpy.ndarray'>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [61]:
arr = np.array([1, 2, 3, 4, 5, 6, 7,9,10])
print(arr[2:6])

[3 4 5 6]


In [63]:
arr = np.array([1, 2, 3, 4, 5, 6, 7,9,10])
print(arr[2:])

[ 3  4  5  6  7  9 10]


In [65]:
arr = np.array([1, 2, 3, 4, 5, 6, 7,9,10])
print(arr[:3])

[1 2 3]


In [67]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-4:-1])

[4 5 6]


In [81]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10],[11,12,13,14,15]])
arr2 = arr[ 0:2,0:3]
print(arr2)
print(type(arr2))

[[1 2 3]
 [6 7 8]]
<class 'numpy.ndarray'>


In [87]:
arr = np.array([   [[1,2],[3,4]  ], [[5,6],[7,8]]  ])
print(arr)
print(arr.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [89]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])


2nd element on 1st row:  2


In [91]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])
print(arr[0][1])

2nd element on 1st row:  2
2


In [95]:
arr = np.arange(1,15,2.5,float)
print(arr)

[ 1.   3.5  6.   8.5 11.  13.5]


In [97]:
arr = np.arange(10,100,5,int)
print("The array over the given range is ",arr)

The array over the given range is  [10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [101]:
arr=np.array([1,2,3,4,5,6,7,8])
x=arr.copy()
arr[3]=32
print(arr)
print(x)

[ 1  2  3 32  5  6  7  8]
[1 2 3 4 5 6 7 8]


In [103]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [107]:
a = np.arange(1, 20,2)
print(a) 
indices = np.array([2, 3, 6])
print(a[indices])

[ 1  3  5  7  9 11 13 15 17 19]
[ 5  7 13]


In [1]:
a = [1,2,3,4,5]
print(a)

[1, 2, 3, 4, 5]


In [3]:
print(a)

[1, 2, 3, 4, 5]
